<a href="https://colab.research.google.com/github/y25246001-MScAIBDA/Python-_Assignment_ML-Projects/blob/main/Credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing the Dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
114957,73690,-2.197480,1.982629,0.259502,0.924323,-0.879938,-0.135952,-0.380186,0.611134,0.278764,...,-0.033516,-0.367199,-0.099698,-0.111166,-0.182825,0.427261,-0.895134,0.164611,9.51,0.0
114958,73690,-2.197480,1.982629,0.259502,0.924323,-0.879938,-0.135952,-0.380186,0.611134,0.278764,...,-0.033516,-0.367199,-0.099698,-0.111166,-0.182825,0.427261,-0.895134,0.164611,9.51,0.0
114959,73690,1.255655,0.293362,0.288616,0.701727,-0.447134,-1.093442,0.029565,-0.155947,0.160172,...,-0.297287,-0.898954,0.139494,0.322281,0.187536,0.097228,-0.028586,0.029014,1.79,0.0
114960,73690,1.270638,-0.089535,-0.990690,-0.375303,0.652307,-0.073908,0.394543,-0.164288,-0.317251,...,-0.067492,-0.344301,-0.372630,-1.296908,0.731021,1.152123,-0.131651,-0.024591,75.00,0.0
114961,73691,1.295784,0.049457,-1.301814,-0.476648,2.131357,3.184446,-0.494416,0.802781,-0.075014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114962 entries, 0 to 114961
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    114962 non-null  int64
 1   V1      114962 non-null  float64
 2   V2      114962 non-null  float64
 3   V3      114962 non-null  float64
 4   V4      114962 non-null  float64
 5   V5      114962 non-null  float64
 6   V6      114962 non-null  float64
 7   V7      114962 non-null  float64
 8   V8      114962 non-null  float64
 9   V9      114962 non-null  float64
 10  V10     114962 non-null  float64
 11  V11     114962 non-null  float64
 12  V12     114961 non-null  float64
 13  V13     114961 non-null  float64
 14  V14     114961 non-null  float64
 15  V15     114961 non-null  float64
 16  V16     114961 non-null  float64
 17  V17     114961 non-null  float64
 18  V18     114961 non-null  float64
 19  V19     114961 non-null  float64
 20  V20     114961 non-null  float64
 21  V21     114961 non-null  float64
 22  V22     114961 non-null  float64
 23  V23     114961 non-null  float64
 24  V24     114961 non-null  float64
 25  V25     114961 non-null  float64
 26  V26     114961 non-null  float64
 27  V27     114961 non-null  float64
 28  V28     114961 non-null  float64
 29  Amount  114961 non-null  float64
 30  Class   114961 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 27.2 MB

In [ ]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.0    114719
1.0       242
Name: count, dtype: int64

This Dataset is highly unblanced

0 --> Normal Transaction

1 --> fraudulent transaction

In [ ]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(114719, 31)
(242, 31)

In [ ]:
# statistical measures of the data
legit.Amount.describe()

count    114719.000000
mean         94.859137
std         257.024232
min           0.000000
25%           6.990000
50%          25.000000
75%          85.250000
max       19656.530000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     242.000000
mean      119.435331
std       254.330814
min         0.000000
25%         1.000000
50%         8.565000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,46095.931415,-0.242322,-0.023224,0.698223,0.145973,-0.274923,0.096444,-0.102075,0.055820,-0.063634,...,0.042648,-0.036798,-0.110409,-0.036248,0.011349,0.132138,0.026597,-0.000104,0.001924,94.859137
1.0,39270.280992,-5.942308,4.133122,-7.591109,4.716339,-4.227089,-1.524018,-6.307479,1.589037,-2.723048,...,0.260058,1.348273,-0.332768,-0.105461,-0.111634,0.210822,0.086947,0.533591,0.065613,119.435331

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [ ]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
106325,69921,1.162978,-1.097519,0.905584,-0.651494,-1.455128,0.051269,-1.066579,0.002200,-0.322047,...,-0.136549,-0.086390,-0.143488,-0.381944,0.064101,1.151312,-0.017963,0.041565,125.90,0.0
95403,65288,1.110416,0.432555,1.099908,2.428785,-0.511673,-0.218627,-0.226065,0.149442,-0.727090,...,-0.156832,-0.604153,0.178204,0.453680,0.092803,-0.284557,-0.002948,0.023437,3.78,0.0
49366,44023,-0.596452,-0.260852,1.473974,-1.772481,-0.807314,-0.193399,0.512660,0.132108,-1.508607,...,0.192677,0.089568,0.416461,0.162345,-0.620304,-0.707667,0.087681,0.149115,146.20,0.0
41667,40777,-13.743681,-13.968721,-1.622761,7.210932,9.007844,-5.505580,-6.912828,-1.297927,0.501298,...,-1.119724,-1.364468,-10.871379,0.870020,-2.890982,0.180594,4.814408,-5.940556,35.15,0.0
82061,59221,-0.042706,-0.044896,0.023371,-2.435074,1.821759,3.344200,-0.455441,0.879321,-1.478523,...,-0.069801,-0.529397,-0.010108,0.969781,-0.038703,-0.506304,0.034393,0.021992,17.99,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
108258,70828,0.196707,1.189757,0.704882,2.891388,0.045555,1.245730,-1.198714,-2.421616,-1.232089,...,-1.328132,0.189311,-0.005524,-0.814708,0.400924,0.286281,0.135215,0.257315,0.76,1.0
108708,71033,-3.170818,0.185735,-3.399852,3.761155,-2.148047,-1.598944,-2.519565,1.316215,-2.400106,...,1.092051,-0.041080,0.904395,0.180016,0.049970,-0.257100,0.859282,0.225924,426.40,1.0
111690,72327,-4.198735,0.194121,-3.917586,3.920748,-1.875486,-2.118933,-3.614445,1.687884,-2.189871,...,0.801312,-0.183001,-0.440387,0.292539,-0.144967,-0.251744,1.249414,-0.131525,238.90,1.0
112840,72824,-1.111495,-0.257575,2.250210,1.152671,0.432904,1.254126,-0.584163,-0.609682,1.014602,...,0.862913,0.927825,-0.343058,-0.256268,-0.600742,-0.180331,0.026762,-0.358335,45.03,1.0
114271,73408,-2.869795,1.335667,-1.009530,1.693885,-0.741480,-0.796773,-2.614242,1.066636,-1.135497,...,0.528421,0.228027,-0.749298,-0.067179,0.215792,-0.453651,0.349191,0.198862,16.48,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0    242
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,46700.024390,-0.301328,-0.004954,0.707249,0.274843,-0.313617,0.170781,-0.139052,0.128589,-0.117944,...,0.026820,-0.061789,-0.121931,-0.051819,0.055536,0.102107,0.029904,0.019799,-0.027287,91.812785
1.0,39270.280992,-5.942308,4.133122,-7.591109,4.716339,-4.227089,-1.524018,-6.307479,1.589037,-2.723048,...,0.260058,1.348273,-0.332768,-0.105461,-0.111634,0.210822,0.086947,0.533591,0.065613,119.435331

Splitting the data into Features & Targets

In [ ]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [ ]:
print(X)

         Time         V1         V2        V3        V4        V5        V6  \
106325  69921   1.162978  -1.097519  0.905584 -0.651494 -1.455128  0.051269
95403   65288   1.110416   0.432555  1.099908  2.428785 -0.511673 -0.218627
49366   44023  -0.596452  -0.260852  1.473974 -1.772481 -0.807314 -0.193399
41667   40777 -13.743681 -13.968721 -1.622761  7.210932  9.007844 -5.505580
82061   59221  -0.042706  -0.044896  0.023371 -2.435074  1.821759  3.344200
...       ...        ...        ...       ...       ...       ...       ...
108258  70828   0.196707   1.189757  0.704882  2.891388  0.045555  1.245730
108708  71033  -3.170818   0.185735 -3.399852  3.761155 -2.148047 -1.598944
111690  72327  -4.198735   0.194121 -3.917586  3.920748 -1.875486 -2.118933
112840  72824  -1.111495  -0.257575  2.250210  1.152671  0.432904  1.254126
114271  73408  -2.869795   1.335667 -1.009530  1.693885 -0.741480 -0.796773

              V7        V8        V9  ...       V20       V21       V22  \
106325 -1.066579  0.002200 -0.322047  ... -0.111790 -0.136549 -0.086390
95403  -0.226065  0.149442 -0.727090  ... -0.196722 -0.156832 -0.604153
49366   0.512660  0.132108 -1.508607  ...  0.260089  0.192677  0.089568
41667  -6.912828 -1.297927  0.501298  ... -6.434565 -1.119724 -1.364468
82061  -0.455441  0.879321 -1.478523  ...  0.272967 -0.069801 -0.529397
...          ...       ...       ...  ...       ...       ...       ...
108258 -1.198714 -2.421616 -1.232089  ...  0.646616 -1.328132  0.189311
108708 -2.519565  1.316215 -2.400106  ...  1.932254  1.092051 -0.041080
111690 -3.614445  1.687884 -2.189871  ...  1.003350  0.801312 -0.183001
112840 -0.584163 -0.609682  1.014602  ... -0.510614  0.862913  0.927825
114271 -2.614242  1.066636 -1.135497  ...  0.011557  0.528421  0.228027

              V23       V24       V25       V26       V27       V28  Amount
106325  -0.143488 -0.381944  0.064101  1.151312 -0.017963  0.041565  125.90
95403    0.178204  0.453680  0.092803 -0.284557 -0.002948  0.023437    3.78
49366    0.416461  0.162345 -0.620304 -0.707667  0.087681  0.149115  146.20
41667  -10.871379  0.870020 -2.890982  0.180594  4.814408 -5.940556   35.15
82061   -0.010108  0.969781 -0.038703 -0.506304  0.034393  0.021992   17.99
...           ...       ...       ...       ...       ...       ...     ...
108258  -0.005524 -0.814708  0.400924  0.286281  0.135215  0.257315    0.76
108708   0.904395  0.180016  0.049970 -0.257100  0.859282  0.225924  426.40
111690  -0.440387  0.292539 -0.144967 -0.251744  1.249414 -0.131525  238.90
112840  -0.343058 -0.256268 -0.600742 -0.180331  0.026762 -0.358335   45.03
114271  -0.749298 -0.067179  0.215792 -0.453651  0.349191  0.198862   16.48

[734 rows x 30 columns]

In [ ]:
print(Y)

106325    0.0
95403     0.0
49366     0.0
41667     0.0
82061     0.0
         ...
108258    1.0
108708    1.0
111690    1.0
112840    1.0
114271    1.0
Name: Class, Length: 734, dtype: float64

Split the data into Training data & Testing Data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(734, 30) (587, 30) (147, 30)

Model Training

Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy Score

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9642248722316865

In [ ]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9319727891156463